name: Build

on: 
  push:

jobs:
  build_window_dll:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cygwin
      uses: egor-tensin/setup-cygwin@v3
      with:
        platform: x64
        packages: 'cmake base-devel'
    - shell: msys2 {0}
      run: |
        C:\tools\cygwin\bin\sh -lc "(./autogen.sh)"
