name: Build

on: 
  push:

jobs:
  build_window_dll:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: 'cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-dlfcn base-devel'
    - shell: msys2 {0}
      run: |
        echo "#! /bin/sh" > /mingw64/bin/make
        echo "\"mingw32-make\" \"\$@\"" >> /mingw64/bin/make
    - shell: msys2 {0}
      run: |
        ./autogen.sh
        ./configure --enable-static --disable-shared
        make
        mkdir -p Dist/Include/ffi/Win64/
        cp x86_64-w64-mingw32/include/ffi.h Dist/Include/ffi/Win64/
        cp x86_64-w64-mingw32/include/ffitarget.h Dist/Include/ffi/Win64/
        mkdir -p Dist/Library/ffi/Win64
        cp x86_64-w64-mingw32/.libs/libffi.a Dist/Library/ffi/Win64/ 
    - uses: actions/upload-artifact@v2
      with:
        name: ffi_bin
        path: Dist/**/*
        