name: Build

on: 
  push:

jobs:
  build_window_dll:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: 'cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-dlfcn base-devel'
    - shell: msys2 {0}
      run: |
        echo "#! /bin/sh" > /mingw64/bin/make
        echo "\"mingw32-make\" \"\$@\"" >> /mingw64/bin/make
    - shell: msys2 {0}
      run: |
        ./autogen.sh
        ./configure CC="msvcc.sh -m64" CXX="msvcc.sh -m64" LD=link CPP="cl -nologo -EP" CPPFLAGS="-DFFI_BUILDING_DLL"
        make
