name: Build

on: 
  push:

jobs:
  build_window_dll:
    name: Windows
    runs-on: windows-2019
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cygwin
      uses: egor-tensin/setup-cygwin@v3
      with:
        platform: x64
        packages: 'cmake make automake gcc gcc-c++'
    - name: Run build script
      run: |
        ./autogen.sh
